Repository ampproject/amp-github-apps, pull requests merged in 2020-04, with the labels that each got.

#768 Update packages for all GitHub apps
  .prettierrc
  build-system/build-targets.js
  build-system/git.js
  bundle-size-chart/package-lock.json
  bundle-size-chart/package.json
  bundle-size-chart/static/index.js
  bundle-size/package-lock.json
  bundle-size/package.json
  checklist/package-lock.json
  checklist/package.json
  invite/package-lock.json
  invite/package.json
  owners/info_server.js
  owners/package-lock.json
  owners/package.json
  owners/test/api/github.test.js
  package-lock.json
  package.json
  pr-deploy/package-lock.json
  pr-deploy/package.json
  release-calendar/package-lock.json
  release-calendar/package.json
  test-status/db.js
  test-status/package-lock.json
  test-status/package.json
Labels: cla: yes

#770 🌿Freshen up package lock files to fix `kind-of` security vulnerability
  bundle-size/package-lock.json
  checklist/package-lock.json
  invite/package-lock.json
  owners/package-lock.json
  pr-deploy/package-lock.json
  pr-deploy/src/github.ts
  release-calendar/package-lock.json
  test-status/package-lock.json
Labels: cla: yes

#772 [release-calendar] Adds more test data
  release-calendar/test/repository-service.ts
  release-calendar/test/test-data.ts
Labels: cla: yes

#773 🙊🙈 Run eslint Travis tests against .ts and .tsx files too 🙈🙊
  .eslintignore
  build-system/pr-check.js
  bundle-size-chart/.eslintrc.js
  bundle-size-chart/src/app.ts
  checklist/.eslintrc.js
  checklist/.gitignore
  checklist/.prettierrc
  checklist/app.ts
  checklist/tsconfig.json
  invite/.eslintrc.js
  invite/.gitignore
  invite/.prettierrc
  invite/app.ts
  invite/src/invitation_record.ts
  invite/test/fixtures/index.ts
  package.json
  pr-deploy/.eslintrc.js
  pr-deploy/jest.config.ts
  pr-deploy/src/github.ts
  release-calendar/test/repository-service.ts
Labels: cla: yes

#777 Project skeleton for Error Issue Bot
  bin/unredact-env.js
  error-issue/.eslintrc.js
  error-issue/.gcloudignore
  error-issue/.gitignore
  error-issue/README.md
  error-issue/cloud_build.yaml
  error-issue/index.ts
  error-issue/package-lock.json
  error-issue/package.json
  error-issue/redacted.env
  error-issue/tsconfig.json
Labels: cla: yes

#781 [error-issue] Creates error-issue bot to glue blame finding and issue creation
  error-issue/index.ts
  error-issue/package-lock.json
  error-issue/package.json
  error-issue/src/blame_finder.stub.ts
  error-issue/src/bot.ts
  error-issue/src/issue_builder.stub.ts
  error-issue/src/rate_limited_graphql.stub.ts
  error-issue/src/types.ts
  error-issue/test/bot.test.ts
Labels: cla: yes

#782 [release-calendar] Updating db schema
  release-calendar/src/client/models/view-models.ts
  release-calendar/src/server/entities/promotion.ts
  release-calendar/src/types.ts
  release-calendar/test/repository-service.ts
  release-calendar/test/test-data.ts
Labels: cla: yes

#776 [release-calendar] Create ChannelTable skeleton
  release-calendar/src/client/components/App.tsx
  release-calendar/src/client/components/Calendar.tsx
  release-calendar/src/client/components/ChannelTable.tsx
  release-calendar/src/client/components/Header.tsx
  release-calendar/src/client/stylesheets/app.scss
  release-calendar/src/client/stylesheets/calendar.scss
  release-calendar/src/client/stylesheets/channelTable.scss
Labels: Category: Release Calendar, cla: yes

#779 [error-issue] Add class for finding `git blame` info for each line of a stacktrace
  error-issue/package.json
  error-issue/src/blame_finder.stub.ts
  error-issue/src/blame_finder.ts
  error-issue/src/bot.ts
  error-issue/src/rate_limited_graphql.ts
  error-issue/src/types.ts
  error-issue/src/utils.ts
  error-issue/test/blame_finder.test.ts
  error-issue/test/bot.test.ts
  error-issue/test/fixtures/2004030010070/extensions-amp-delight-player-0_1-amp-delight-player_js.json
  error-issue/test/fixtures/2004030010070/extensions-amp-next-page-1_0-service_js.json
  error-issue/test/fixtures/2004030010070/src-event-helper-listen_js.json
  error-issue/test/fixtures/index.ts
  error-issue/test/fixtures/master/src-log_js.json
  error-issue/test/fixtures/not-a-ref/src-log_js.json
  error-issue/test/jest-preload.ts
  error-issue/test/rate_limited_graphql.test.ts
  error-issue/test/utils.test.ts
Labels: cla: yes

#784 [release-calendar] Event Handling
  release-calendar/src/client/components/App.tsx
  release-calendar/src/client/components/Calendar.tsx
  release-calendar/src/client/components/ChannelTable.tsx
  release-calendar/src/client/models/release-event.ts
Labels: Category: Release Calendar, cla: yes

#780 [error-issue] Add helper class to build error report issues
  error-issue/index.ts
  error-issue/src/bot.ts
  error-issue/src/issue_builder.stub.ts
  error-issue/src/issue_builder.ts
  error-issue/src/utils.ts
  error-issue/test/bot.test.ts
  error-issue/test/fixtures/created-issue.md
  error-issue/test/fixtures/index.ts
  error-issue/test/issue_builder.test.ts
  error-issue/test/utils.test.ts
Labels: cla: yes

#789 [error-issue] (XS) Add "http://" to link URL
  error-issue/src/issue_builder.ts
  error-issue/test/fixtures/created-issue.md
  error-issue/test/issue_builder.test.ts
Labels: cla: yes

#785 [release-calendar] Header
  release-calendar/src/client/components/Calendar.tsx
  release-calendar/src/client/components/Header.tsx
  release-calendar/src/client/stylesheets/header.scss
Labels: Category: Release Calendar, cla: yes

#786 [release-calendar] Change location of shared colors
  release-calendar/package-lock.json
  release-calendar/package.json
  release-calendar/src/client/models/release-event.ts
  release-calendar/src/client/stylesheets/_base.scss
  release-calendar/src/client/stylesheets/app.scss
  release-calendar/src/client/stylesheets/calendar.scss
  release-calendar/src/client/stylesheets/channelTable.scss
  release-calendar/webpack.client.config.js
Labels: Category: Release Calendar, cla: yes

#774 [release-calendar] Add api call getCurrentReleases
  release-calendar/.eslintrc.js
  release-calendar/src/client/api-service.ts
  release-calendar/src/client/components/ChannelTable.tsx
  release-calendar/src/client/models/view-models.ts
  release-calendar/src/server/app.ts
  release-calendar/src/server/entities/promotion.ts
  release-calendar/src/server/repository-service.ts
  release-calendar/src/types.ts
Labels: Category: Release Calendar, cla: yes

#792 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: cla: yes

#793 Add build target for error issue bot tests
  build-system/build-targets.js
  build-system/pr-check.js
Labels: cla: yes

#790 Add module to monitor errors in GCP and identify new untracked ones
  error-issue/cloud_build.yaml
  error-issue/index.ts
  error-issue/package-lock.json
  error-issue/package.json
  error-issue/redacted.env
  error-issue/src/error_monitor.ts
  error-issue/src/stackdriver_api.ts
  error-issue/src/types.ts
  error-issue/test/error_monitor.test.ts
Labels: cla: yes

#794 [error-issue] Identify possible assignees for issues
  error-issue/src/issue_builder.ts
  error-issue/test/fixtures/created-issue.md
  error-issue/test/issue_builder.test.ts
Labels: cla: yes

#798 [test-status] update build-cop/report endpoint to use new data format
  test-status/api.js
  test-status/test/api.test.js
Labels: Category: Test Status, cla: yes

#796 [owners] Fix team @ mentions
  owners/index.js
  owners/src/api/github.js
  owners/src/notifier.js
  owners/test/api/github.test.js
  owners/test/notifier.test.js
Labels: cla: yes

#801 [error-issue] Add auto-linking of created issue to GCP error
  error-issue/index.ts
  error-issue/package.json
  error-issue/src/stackdriver_api.ts
Labels: cla: yes

#804 [error-issue] Add auto-linking of created issue to GCP error
  error-issue/index.ts
  error-issue/package.json
  error-issue/src/stackdriver_api.ts
Labels: cla: yes

#795 [release-calendar] Add api call getReleases for all releases
  release-calendar/src/client/api-service.ts
  release-calendar/src/client/components/Calendar.tsx
  release-calendar/src/client/models/release-event.ts
  release-calendar/src/client/models/view-models.ts
  release-calendar/src/client/stylesheets/_base.scss
  release-calendar/src/client/stylesheets/channelTable.scss
  release-calendar/src/server/repository-service.ts
  release-calendar/src/types.ts
Labels: Category: Release Calendar, cla: yes

#797 [release-calendar] Remove Rollbacks from Channel enum
  release-calendar/src/server/repository-service.ts
  release-calendar/src/types.ts
Labels: Category: Release Calendar, cla: yes

#802 [error-issue] Fix handling of lines with no associated blame info
  error-issue/src/blame_finder.ts
  error-issue/src/issue_builder.ts
  error-issue/src/types.ts
  error-issue/test/blame_finder.test.ts
  error-issue/test/fixtures/2004172112280/extensions-amp-base-carousel-0_1-dimensions_js.json
  error-issue/test/issue_builder.test.ts
Labels: cla: yes

#806 [owners] Consolidate notification comments by grouping file lists
  owners/src/api/github.js
  owners/src/notifier.js
  owners/test/api/github.test.js
  owners/test/notifier.test.js
Labels: cla: yes

#807 [release-calendar] 🐛 Remove getCurrentReleases bug 🐛
  release-calendar/src/server/repository-service.ts
Labels: Category: Release Calendar, cla: yes

#808 [onduty] Add project boilerplate for onduty bot
  onduty/.eslintrc.js
  onduty/.gcloudignore
  onduty/.gitignore
  onduty/README.md
  onduty/cloud_build.yaml
  onduty/index.ts
  onduty/package-lock.json
  onduty/package.json
  onduty/redacted.env
  onduty/tsconfig.json
Labels: cla: yes

#811 [onduty] Add GitHub API interface for fetching/updating team info
  onduty/package.json
  onduty/src/github.ts
  onduty/test/github.test.ts
  onduty/test/jest-preload.ts
  onduty/tsconfig.json
  onduty/types/index.d.ts
Labels: cla: yes

#812 [onduty] Add Onduty Bot to handle rotation updates and update teams
  onduty/package-lock.json
  onduty/package.json
  onduty/src/bot.ts
  onduty/test/bot.test.ts
  onduty/types/index.d.ts
Labels: cla: yes

#805 [release-calendar] Add getRelease()
  release-calendar/src/client/api-service.ts
  release-calendar/src/client/components/App.tsx
  release-calendar/src/client/components/Calendar.tsx
  release-calendar/src/client/components/ChannelTable.tsx
  release-calendar/src/client/models/release-event.ts
  release-calendar/src/client/models/view-models.ts
  release-calendar/src/server/app.ts
  release-calendar/src/server/repository-service.ts
Labels: Category: Release Calendar, cla: yes

#814 Define root ES6 and TS eslint configs
  .eslintrc
  .eslintrc-es6.js
  .eslintrc-ts.js
  onduty/.eslintrc.js
Labels: cla: yes

#815 [onduty] Add handlers to receive rotation updates
  onduty/cloud_build.yaml
  onduty/index.ts
  onduty/package-lock.json
  onduty/package.json
  onduty/redacted.env
  onduty/src/bot.ts
  onduty/test/e2e.test.ts
  onduty/test/jest-preload.ts
  onduty/types/index.d.ts
Labels: cla: yes
