Repository ampproject/amp-github-apps, pull requests merged in 2021-06, with the labels that each got.

#1340 Update owners schema to allow bot owners
  owners/src/ownership/schema.json
  owners/test/ownership/parser.test.js
Labels: Category: Owners

#1341 Enable auto-merging of upgrade PRs if CI is green
  renovate.json
Labels: Category: Infrastructure

#1342 More grouping fixes
  renovate.json
Labels: Category: Infrastructure

#1368 Disable auto-rebasing of update PRs
  renovate.json
Labels: Category: Infrastructure

#1369 Consolidate and standardize all linting at the root level
  .eslintignore
  .eslintrc-ts.js
  build-system/pr-check.js
  bundle-size-chart/.eslintrc.js
  bundle-size-chart/package-lock.json
  bundle-size-chart/package.json
  bundle-size/package-lock.json
  bundle-size/package.json
  error-monitoring/.eslintrc.js
  error-monitoring/app.ts
  error-monitoring/index.ts
  error-monitoring/package-lock.json
  error-monitoring/package.json
  error-monitoring/src/error_monitor.ts
  error-monitoring/src/stackdriver_api.ts
  error-monitoring/src/utils.ts
  error-monitoring/test/error_monitor.test.ts
  error-monitoring/test/fixtures/index.ts
  invite/.eslintrc.js
  invite/app.ts
  invite/package-lock.json
  invite/package.json
  invite/src/db.ts
  invite/types/invite-bot.d.ts
  onduty/.eslintrc.js
  onduty/index.ts
  onduty/package-lock.json
  onduty/package.json
  onduty/test/bot.test.ts
  onduty/test/e2e.test.ts
  onduty/test/github.test.ts
  owners/package-lock.json
  owners/package.json
  owners/test/index.test.js
  package-lock.json
  package.json
  pr-deploy/.eslintrc.js
  pr-deploy/package-lock.json
  pr-deploy/package.json
  pr-deploy/src/app.ts
  pr-deploy/src/zipper.ts
  pr-deploy/test/app.test.ts
  release-calendar/.eslintignore
  release-calendar/.eslintrc.js
  release-calendar/package-lock.json
  release-calendar/package.json
  release-calendar/src/client/components/Calendar.tsx
  release-calendar/src/client/components/ChannelTable.tsx
  test-case-reporting/.eslintrc.js
  test-case-reporting/app.ts
  test-case-reporting/index.ts
  test-case-reporting/package-lock.json
  test-case-reporting/package.json
  test-case-reporting/src/db.ts
  test-case-reporting/src/setup_db.ts
  test-case-reporting/test/test_result_record.test.ts
  test-status/package-lock.json
  test-status/package.json
Labels: Category: Infrastructure

#1375 Don't hide repo-wide lint behind test during CI
  build-system/pr-check.js
  build-system/utils.js
  package.json
Labels: Category: Infrastructure

#1393 Refine automerge assignment logic
  renovate.json
Labels: Category: Infrastructure

#1317 Add a new GitHub app that publishes any webhook it receives to a Cloud Pub/Sub topic
  README.md
  build-system/build-targets.js
  renovate.json
  webhook-pubsub-publisher/.eslintrc.js
  webhook-pubsub-publisher/.gcloudignore
  webhook-pubsub-publisher/.gitignore
  webhook-pubsub-publisher/README.md
  webhook-pubsub-publisher/cloud_build.yaml
  webhook-pubsub-publisher/package-lock.json
  webhook-pubsub-publisher/package.json
  webhook-pubsub-publisher/redacted.env
  webhook-pubsub-publisher/src/app.ts
  webhook-pubsub-publisher/src/index.ts
  webhook-pubsub-publisher/test/app.test.ts
  webhook-pubsub-publisher/tsconfig.json
  webhook-pubsub-publisher/types/probot__serverless-gcf.d.ts
Labels: Category: Webhook Pub/Sub Publisher
